os: linux
dist: xenial
language: node_js
node_js:
  - 12

env:
  global:
    # - NX_BRANCH: $TRAVIS_PULL_REQUEST_BRANCH # The pull request branch
    - NX_BRANCH=$TRAVIS_PULL_REQUEST # The pull request number
    - NX_RUN_GROUP=$TRAVIS_BUILD_ID

install:
  - yarn
script:
  - echo "$NX_BRANCH"
  - echo "$NX_RUN_GROUP"
  - yarn nx affected:test --scan
  - node tools/env-test.js
